apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: Kustomization
metadata:
  name: backapi
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: java-sample-apps
  path: ./manifests