FROM gradle:jdk11 as builder

WORKDIR /home/gradle/src
COPY --chown=gradle:gradle . /home/gradle/src
RUN gradle build

FROM mcr.microsoft.com/openjdk/jdk:11-ubuntu

EXPOSE 8080
WORKDIR /app
COPY --from=builder /home/gradle/src/build/libs/*.jar ./app.jar
ENTRYPOINT ["java", "-Xmx128M", "-XX:+FlightRecorder", "-XX:+PrintFlagsFinal", "-jar", "app.jar"]⏎
