apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backapi
  name: backapi
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backapi
  strategy: {}
  template:
    metadata:
      labels:
        app: backapi
    spec:
      containers:
      - image: ghcr.io/levi106/backapi:0.0.4-distroless
        name: backapi
        env:
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: ai
              key: connectionstring
        resources: 
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
