apiVersion: v1
kind: Service
metadata:
  labels:
    app: backapi
  name: backapi
  namespace: backapi
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: backapi
  type: LoadBalancer
  loadBalancerIP: 192.168.2.254