apiVersion: v1
kind: Service
metadata:
  labels:
    app: dbtest
  name: dbtest
  namespace: dbtest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: dbtest
  type: LoadBalancer
