name: DeployFluxctl

on:
  workflow_dispatch:

env:
  NAMESPACE: flux

jobs:
  deploy-fluxctl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set k8s context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Setup fluxctl
        uses: fluxcd/fluxctl-action@master
        
      - name: Create namespace if does not exist
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
        
      - name: Install Flux
        run: |
          fluxctl install \
          --git-path=manifests \
          --git-branch=main \
          --git-readonly=true \
          --registry-disable-scanning=true \
          --git-email=16788901+levi106@users.noreply.github.com \
          --git-url=https://github.com/levi106/java-sample-apps.git \
          --namespace=${{ env.NAMESPACE }} | kubectl apply -f -
      
      - name: Verify install
        run: kubectl -n ${{ env.NAMESPACE }} rollout status deploy/flux --timeout=1m
        
      - name: Sync git with cluster
        env:
          FLUX_FORWARD_NAMESPACE: flux
        run: fluxctl sync
