name: DeployFluxctl

on:
  workflow_dispatch:

env:
  NAMESPACE: flux-system
  GITHUB_REPO: java-sample-apps
  GITHUB_USER: levi106

jobs:
  deploy-fluxctl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set k8s context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Setup fluxctl
        uses: fluxcd/fluxctl-action@master
        
      - name: Install Flux
        run: |
          flux bootstrap github \
          --context=production \
          --owner=${{ env.GITHUB_USER }}
          --repository=${{ env.GITHUB_REPO }}
          --branch=main \
          --path=clusters/production \
          --personal \
          --namespace=${{ env.NAMESPACE }} | kubectl apply -f -
      
      - name: Verify install
        run: kubectl -n ${{ env.NAMESPACE }} rollout status deploy/flux --timeout=1m
